#x="Hi hEllo pythonh123 Hi"
# # print(x.split())
# # print(x.split('h'))
# # print(x.split('h',3))
# # print(x.split('h',1))
# # print(x.capitalize())
# # print(x.casefold())
# # print(x.center(20,'o'))
# # print(x.count("h",0,29))
# # print(x.encode())
# # print(x.endswith("h"))
# # print(x.expandtabs(5))
# # print(x.find("i"))
# # print(x.find("h",4,16))
# # print(x.isalnum())
# # print(x.isalpha())
# # print(x.isascii())
# # print(x.isdigit())
# # print(x.isdecimal())
# # print(x.islower())
# # print(x.isnumeric())
# # print(x.istitle())
# print(x.replace("Hi","java",2))
# print(x.title())
# print(x.startswith("Hi"))
# print(x.strip("Hi"))
# print(x.upper())
# print(x.lower())

#Lists
# x=[]
# for i in range(1,5):
#     y= int(input("enter x values for list"))
#     x.append(y)
# print(x)

x=[1,20,10,50]
# x.reverse()
# print(x)
# x.sort()
# print(x)
# print(x.count(10))
# print(x.copy())
# print(x.pop())
# print(x)
# print(x.pop(1))
# print(x)
x.insert(1,100)
print(x)

